# Generated by Django 4.0.4 on 2022-05-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="last_child_created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
